common:
  workerNum: 5
  fileDir: ebooks
  cookie: your-cookie
  cn: true
cn:
  listUrl: https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll
  ajaxUrl: https://www.amazon.cn/hz/mycd/ajax
com:
  listUrl: https://www.amazon.com/hz/mycd/myx#/home/content/booksAll
  ajaxUrl: https://www.amazon.com/hz/mycd/ajax
