# main.yml
name: Build and Release Kindle-Download

on:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      # 发布到 Release
      - 
        name: Release Kindle-Download
        uses: ncipollo/release-action@v1.5.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
